### PR TITLE
Remove Google Play Services dependency

### PR DESCRIPTION
**Pull request by gjedeer**
Switch from upstream android-job library to no-gplay fork maintained by mat-dr https://github.com/mat-dr/android-job

Dyskusja -> https://github.com/feelfreelinux/WykopMobilny/issues/68

### CODE REVIEW

**Comment by gjedeer** [comment]
Done

**Comment by gjedeer** [comment]
BTW, bugsnag is going to be a problem too, but I guess the only way to solve that is a build flavor

**Comment by feelfreelinux** [comment]
@gjedeer I saw few F-droid projects using bugsnag, bugsnag-android is opensource library

**Comment by mdczaplicki** [comment]
Hey, happened during deployment of app from Android Studio. After crash app works fine.

```
java.lang.RuntimeException: Unable to instantiate service com.evernote.android.job.gcm.PlatformGcmService: java.lang.ClassNotFoundException: com.evernote.android.job.gcm.PlatformGcmService
    at android.app.ActivityThread.handleCreateService(ActivityThread.java)
    at android.app.ActivityThread.-wrap5(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.ClassNotFoundException: com.evernote.android.job.gcm.PlatformGcmService
    at java.lang.VMClassLoader.findLoadedClass(Native Method)
    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 9 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GcmTaskService;
    at com.evernote.android.job.GcmAvailableHelper.isGcmApiSupported(GcmAvailableHelper.java)
    at com.evernote.android.job.JobApi.isSupported(JobApi.java:125)
    at com.evernote.android.job.JobProxy$Common.cleanUpOrphanedJob(JobProxy.java:270)
    at com.evernote.android.job.JobManager.schedule(JobManager.java:184)
    at com.evernote.android.job.JobRequest.schedule(JobRequest.java:406)
    at io.github.feelfreelinux.wykopmobilny.ui.modules.notifications.notificationsservice.WykopNotificationsJob$Companion.schedule(WykopNotificationsJob.kt:46)
    at io.github.feelfreelinux.wykopmobilny.ui.modules.mainnavigation.MainNavigationActivity.onCreate(MainNavigationActivity.kt:141)
    at android.app.Activity.performCreate(Activity.java)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    ... 7 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmTaskService" on path: DexPathList[[zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/base.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_dependencies_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_0_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_1_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_2_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_3_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_4_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_5_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_6_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_7_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_8_apk.apk", zip file "/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.github.feelfreelinux.wykopmobilny-2/lib/arm64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 19 more
```

**Comment by feelfreelinux** [comment]
@mdczaplicki Propably notification service is not working after this crash. @gjedeer I think that I'll need to revert this PR unless we'll find another solution.

**Comment by gjedeer** [comment]
@feelfreelinux there is another fork, it looks like this one didn't remove the gsf dependency completely. I'll try to test the other one.

On January 24, 2018 10:01:48 PM GMT+01:00, Marek Czaplicki <notifications@github.com> wrote:
>Hey, happened during deployment of app from Android Studio. After crash
>app works fine.
>
>```
>java.lang.RuntimeException: Unable to instantiate service
>com.evernote.android.job.gcm.PlatformGcmService:
>java.lang.ClassNotFoundException:
>com.evernote.android.job.gcm.PlatformGcmService
> at android.app.ActivityThread.handleCreateService(ActivityThread.java)
>    at android.app.ActivityThread.-wrap5(ActivityThread.java)
>    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
>    at android.os.Handler.dispatchMessage(Handler.java)
>    at android.os.Looper.loop(Looper.java)
>    at android.app.ActivityThread.main(ActivityThread.java)
>    at java.lang.reflect.Method.invoke(Native Method)
>at
>com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
>Caused by: java.lang.ClassNotFoundException:
>com.evernote.android.job.gcm.PlatformGcmService
>    at java.lang.VMClassLoader.findLoadedClass(Native Method)
>    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>    ... 9 more
>Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
>Lcom/google/android/gms/gcm/GcmTaskService;
>at
>com.evernote.android.job.GcmAvailableHelper.isGcmApiSupported(GcmAvailableHelper.java)
>    at com.evernote.android.job.JobApi.isSupported(JobApi.java:125)
>at
>com.evernote.android.job.JobProxy$Common.cleanUpOrphanedJob(JobProxy.java:270)
>   at com.evernote.android.job.JobManager.schedule(JobManager.java:184)
>   at com.evernote.android.job.JobRequest.schedule(JobRequest.java:406)
>at
>io.github.feelfreelinux.wykopmobilny.ui.modules.notifications.notificationsservice.WykopNotificationsJob$Companion.schedule(WykopNotificationsJob.kt:46)
>at
>io.github.feelfreelinux.wykopmobilny.ui.modules.mainnavigation.MainNavigationActivity.onCreate(MainNavigationActivity.kt:141)
>    at android.app.Activity.performCreate(Activity.java)
>at
>android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
>at
>android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
>at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
>    at android.app.ActivityThread.-wrap12(ActivityThread.java)
>    ... 7 more
>Caused by: java.lang.ClassNotFoundException: Didn't find class
>"com.google.android.gms.gcm.GcmTaskService" on path: DexPathList[[zip
>file "/data/app/io.github.feelfreelinux.wykopmobilny-2/base.apk", zip
>file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_dependencies_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_0_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_1_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_2_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_3_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_4_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_5_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_6_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_7_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_8_apk.apk",
>zip file
>"/data/app/io.github.feelfreelinux.wykopmobilny-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.github.feelfreelinux.wykopmobilny-2/lib/arm64,
>/system/lib64, /vendor/lib64]]
>at
>dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>    ... 19 more
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/feelfreelinux/WykopMobilny/pull/70#issuecomment-360271964

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gjedeer** [comment]
@mdczaplicki any idea how to reproduce that? The stack trace gives some idea on how to fix it but a clear way to reproduce would be great.

**Pull request merged**
