### PR TITLE
Fix various LINT issues

### PR DESCRIPTION
**Pull request by michaldrabik**
Decided to jump in and kick off with some misc. fixes of unused symbols, classes and a lot of grey code. Feel free to check it out and review.

Also consider changing minApi to 16 - quite a lot of methods that will crash on 15 and it's only like 0.3% of distribution.

Pozdro

### CODE REVIEW

**Comment by feelfreelinux** [comment]
Been busy lately so I couldn't take a look into it.

The project has gone through a lot of different refactors in last few months. Most of *widget code can be deleted, as it's replaced with bare viewholders. This PR removed a lot of unnecessary code

**Comment by feelfreelinux** [comment]
I'll remove remaining deprecated code in next week

**Comment by feelfreelinux** [comment]
Thank you! If you want access to api keys, DM me on discord / Wykop @michaldrabik

**Comment by michaldrabik** [comment]
@feelfreelinux Already got them. I'll try to walk through all the code and submit further PRs with clean code and consistency refactors (when i got time hehe).

**Pull request merged**
