### PR TITLE
Test cases for login presenter

### PR DESCRIPTION
**Pull request by altaf933**
Here, I have added test case for login presenter and mock class triggered the api.
Also commented a `Log` method from login presenter class cause they are static class and add  to discover into test coverage we have to use `PowerMock`.

### CODE REVIEW

**Comment by feelfreelinux** [comment]
https://travis-ci.org/feelfreelinux/WykopMobilny/builds/347222719?utm_source=github_status&utm_medium=notification

**Comment by feelfreelinux** [comment]
travis fails to build it

**Comment by altaf933** [comment]
Yeah, it fixed and build successful. Actually I have made `Log` line commented cause it's static class and test runner `Mockito` can not handle final static class.

**Comment by altaf933** [comment]
Yeah, it fixed and build successful. Actually I have made `Log` line commented cause it's static class and test runner `Mockito` can not handle final static class.

**Comment by altaf933** [comment]
Looking forward to add more test cases but it's in different language and less knowledge of application. :P

**Pull request merged**
